Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kirigami' : '@same'
    'frameworks/kiconthemes' : '@same'
    'frameworks/kconfigwidgets' : '@same'
    'frameworks/sonnet' : '@same'

Options:
  test-before-installing: True
