Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
   'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kirigami': '@same'
    'frameworks/kiconthemes': '@same'
    'frameworks/sonnet': '@same'
    'frameworks/kcolorscheme': '@same'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
